/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteRouteImport } from './routes/teste'
import { Route as ChatPrivadoRouteImport } from './routes/chat-privado'
import { Route as IndexRouteImport } from './routes/index'

const TesteRoute = TesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPrivadoRoute = ChatPrivadoRouteImport.update({
  id: '/chat-privado',
  path: '/chat-privado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/teste': typeof TesteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/teste': typeof TesteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-privado': typeof ChatPrivadoRoute
  '/teste': typeof TesteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat-privado' | '/teste'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat-privado' | '/teste'
  id: '__root__' | '/' | '/chat-privado' | '/teste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatPrivadoRoute: typeof ChatPrivadoRoute
  TesteRoute: typeof TesteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste': {
      id: '/teste'
      path: '/teste'
      fullPath: '/teste'
      preLoaderRoute: typeof TesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-privado': {
      id: '/chat-privado'
      path: '/chat-privado'
      fullPath: '/chat-privado'
      preLoaderRoute: typeof ChatPrivadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatPrivadoRoute: ChatPrivadoRoute,
  TesteRoute: TesteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
